/**************************************************************************
;* 
;*************************************************************************/
// ICONS
#define IDI_SPICON                      101

// MENU ITEMS
#define IDM_ABOUT                       101

// DIALOGS
#define IDD_LOGSYM                      101

#define IDC_EXIT                        1000
#define IDC_FILENAME                    1001
#define IDC_BROWSE                      1002
#define IDC_VIEW                        1003
#define IDC_LOAD                        1004
#define IDC_APPEND                      1005
#define IDC_MOVE                        1006

#define IDC_MODLIST                     1007
#define IDC_ADD                         1008
#define IDC_REMOVE                      1009
#define IDC_SYMINFO                     1010
#define IDC_STATIC                      -1
