/**************************************************************************
; Written by: Mehdi Sotoodeh
;
; THIS SOFTWARE IS PROVIDED BY THE AUTHORS ''AS IS'' AND ANY EXPRESS
; OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
; WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
; ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHORS OR CONTRIBUTORS BE
; LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
; CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
; SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
; BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
; WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
; OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
; EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;*************************************************************************/

// ICONS
#define IDI_SPICON                      101

// MENU ITEMS
#define IDM_ABOUT                       101

// DIALOGS
#define IDD_LOGSYM                      101

#define IDC_EXIT                        1000
#define IDC_FILENAME                    1001
#define IDC_BROWSE                      1002
#define IDC_VIEW                        1003
#define IDC_LOAD                        1004
#define IDC_APPEND                      1005
#define IDC_MOVE                        1006

#define IDC_MODLIST                     1007
#define IDC_ADD                         1008
#define IDC_REMOVE                      1009
#define IDC_SYMINFO                     1010
#define IDC_STATIC                      -1
